version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=sample_development
      - MYSQL_USER=sample_user
      - MYSQL_PASSWORD=sample_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USERNAME=sample_user
      - DB_PASSWORD=sample_password
      - RAILS_ENV=development
    depends_on:
      - db
    ports:
      - "3000:3000"
    command:
      - bash
      - -c
      - |
        chmod +x /wait-for-it.sh
        /wait-for-it.sh db:3306 -t 60
        rake db:migrate
        rails s -p 3000 -b 0.0.0.0
    volumes:
      - ./:/usr/src/app

